### ISSUE TITLE
ros-noetic-libfranka fails to build due to one or more files not passing validity check

### ISSUE THREAD

**Issue by ruturajsambhusvt** [ros-noetic-arch/ros-noetic-libfranka#3]
Hello, I was trying to install ros-noetic-franka-ros (yay -S package name) and it failed due to the ros-noetic-libfranka SHA validity error. I then used yay to get ros-noetic-libfranka and got the follwing error (attached out.txt)-

ERROR: One or more files did not pass the validity check!
error: failed to download sources for 'ros-noetic-libfranka-0.8.0-2': 
error: packages failed to build: ros-noetic-libfranka-0.8.0-2

Great if you can help!
[out.txt](https://github.com/ros-noetic-arch/ros-noetic-libfranka/files/9096259/out.txt)

**Comment by acxz** [comment]
thx for the report!

closed with b9354b0

**Comment by ruturajsambhusvt** [comment]
Thank you so much!
I see that it installs 0.9.0 version. I have libfranka 0.8.0 installed and might need 0.8.0 version for ros-noetic-libfranka and ros-noetic-franka-ros. Great to know how to do that!

**Comment by acxz** [comment]
You are right I should probably update those as well. If I don't get around to it, you can create a pull request to the associated repository and I'll merge it in! Feel free to ask questions.

**Comment by ruturajsambhusvt** [comment]
Thank you for your response. I am new to Arch Linux and building packages, but I can try to change it if you can give me some directions. I was looking up to find the sha256 for the release but could not find one. I guess I need to change the pkgver to 0.8.0 and sha256sums in the PKGBUILD.

**Comment by acxz** [comment]
Yep that's right. To find the sha256sum, you can run the command `sha256sum *.tar.gz` and copy paste the output to the PKGBUILD. Make sure to also create the `.SRCINFO` file by running `makepkg --printsrcinfo > .SRCINFO`.
