### ISSUE TITLE
ros-noetic-libfranka-0.8.0 fails to build 

### ISSUE THREAD

**Issue by ruturajsambhusvt** [ros-noetic-arch/ros-noetic-libfranka#5]
Hello, I updated the PKGBUILD for 0.8.0-1 and it fails to build. I am attaching herewith the error log.

[out.log](https://github.com/ros-noetic-arch/ros-noetic-libfranka/files/9106698/out.log)

**Comment by acxz** [comment]
Ah this should be an easy fix, the new version `0.9.0` already has the fix, but `0.8.0` does not. However, you can manually add a patch for the fix.

See the following commit: https://github.com/ros-noetic-arch/ros-noetic-libfranka/tree/3ca7e0e3c637458c73cc94fcad268b1b6ef1eeab

on how the include patch is added. In fact, I'd recommend you use that version of the PKGBUILD and just update the sha256sums.

**Comment by ruturajsambhusvt** [comment]
Thank you, I tried it and it builds. The ros-noetic-franka-ros still fails and I will open a new issue there. Sorry for inconvenience :)

**Comment by acxz** [comment]
No worries! Yeah feel free to open as many issues as you need to.
